name: "test"

on:
  push:
    branch:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Test
        working-directory: .
        run: ./gradlew test

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Copy repo to cloud
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          source: "./"
          target: "~/prod"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          script: |
            cd ~/prod
            docker-compose down && docker-compose up --build -d




