name: "dropwizard-ci-pipeline"

on:
  push:
    branch:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Test
        working-directory: .
        run: ./gradlew test

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Copy repo to VM
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.key }}
        with:
          source: "./"
          target: "~/prod"






